# Generated by Django 5.0.4 on 2024-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_points',
            field=models.IntegerField(default=0),
        ),
    ]
