# Generated by Django 5.0.4 on 2025-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_alter_bet_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
