# Generated by Django 5.0.4 on 2025-06-26 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_bet_bet_id'),
        ('tournament', '0046_game_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcards',
            name='most_banned_champion',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcards_most_banned_champion', to='tournament.champion'),
        ),
        migrations.AlterField(
            model_name='wildcards',
            name='most_picked_bot',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcards_most_picked_bot', to='tournament.champion'),
        ),
        migrations.AlterField(
            model_name='wildcards',
            name='most_picked_jgl',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcards_most_picked_jgl', to='tournament.champion'),
        ),
        migrations.AlterField(
            model_name='wildcards',
            name='most_picked_mid',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcards_most_picked_mid', to='tournament.champion'),
        ),
        migrations.AlterField(
            model_name='wildcards',
            name='most_picked_sup',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcards_most_picked_sup', to='tournament.champion'),
        ),
        migrations.AlterField(
            model_name='wildcards',
            name='most_picked_top',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcards_most_picked_top', to='tournament.champion'),
        ),
        migrations.AlterField(
            model_name='wildcards',
            name='player_with_most_assists',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcards_player_with_most_assists', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='wildcards',
            name='player_with_most_deaths',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcards_player_with_most_deaths', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='wildcards',
            name='player_with_most_kills',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcards_player_with_most_kills', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='wildcards',
            name='tournament_winner',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcards_tournament_winner', to='tournament.team'),
        ),
    ]
