# Generated by Django 5.0.4 on 2024-04-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_match_match_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_timedate',
            field=models.DateTimeField(default='2024-04-30T11:00:00'),
        ),
    ]
