# Generated by Django 5.0.4 on 2024-04-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_match_users_who_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1_score',
            field=models.CharField(blank=True, default='?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_score',
            field=models.CharField(blank=True, default='?', max_length=1, null=True),
        ),
    ]
