# Generated by Django 5.0.4 on 2024-04-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_match_team1_score_alter_match_team2_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(),
        ),
    ]
