# Generated by Django 5.0.4 on 2024-09-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_games', models.IntegerField(blank=True, null=True)),
                ('total_dmg', models.IntegerField(blank=True, null=True)),
                ('total_cs', models.IntegerField(blank=True, null=True)),
                ('total_kills', models.IntegerField(blank=True, null=True)),
                ('total_assists', models.IntegerField(blank=True, null=True)),
                ('total_deaths', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvp', models.CharField(blank=True, max_length=50, null=True)),
                ('team_1_picks', models.CharField(blank=True, max_length=200, null=True)),
                ('team_2_picks', models.CharField(blank=True, max_length=200, null=True)),
                ('team_1_bans', models.CharField(blank=True, max_length=200, null=True)),
                ('team_2_bans', models.CharField(blank=True, max_length=200, null=True)),
                ('team_1_team_stats', models.CharField(blank=True, max_length=500, null=True)),
                ('team_2_team_stats', models.CharField(blank=True, max_length=500, null=True)),
                ('team_1_players_stats', models.CharField(blank=True, max_length=1500, null=True)),
                ('team_2_players_stats', models.CharField(blank=True, max_length=1500, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournament.match')),
            ],
        ),
    ]
