# Generated by Django 5.0.4 on 2024-09-19 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_player_match_match_id_team_full_name_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_timedate',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 11, 0)),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
