# Generated by Django 5.0.4 on 2024-09-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_alter_match_match_timedate_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
