# Generated by Django 5.0.4 on 2024-09-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_alter_match_game_type_alter_match_team_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='game_type',
            new_name='match_type',
        ),
    ]
