# Generated by Django 5.0.4 on 2024-09-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_alter_game_mvp_alter_game_team_1_bans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_number',
            field=models.IntegerField(default=5, unique=True),
            preserve_default=False,
        ),
    ]
