# Generated by Django 5.0.4 on 2024-09-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_game_game_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team_1_bans',
            new_name='team_1_bans_json',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_1_picks',
            new_name='team_1_picks_json',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_1_players_stats',
            new_name='team_1_players_stats_json',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_1_team_stats',
            new_name='team_1_team_stats_json',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_2_bans',
            new_name='team_2_bans_json',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_2_picks',
            new_name='team_2_picks_json',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_2_players_stats',
            new_name='team_2_players_stats_json',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_2_team_stats',
            new_name='team_2_team_stats_json',
        ),
    ]
