# Generated by Django 5.0.4 on 2024-09-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_rename_team_1_bans_game_team_1_bans_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_1_bans_json',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_1_picks_json',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_1_players_stats_json',
            field=models.JSONField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_1_team_stats_json',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_2_bans_json',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_2_picks_json',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_2_players_stats_json',
            field=models.JSONField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_2_team_stats_json',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
    ]
