# Generated by Django 5.0.4 on 2024-09-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_alter_game_team_1_bans_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_number',
            field=models.IntegerField(),
        ),
    ]
