# Generated by Django 5.0.4 on 2024-09-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='side_imgs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
