# Generated by Django 5.0.4 on 2024-09-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_game_length_game_score_game_side_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='side_imgs',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
    ]
