# Generated by Django 5.0.4 on 2024-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_match_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_odds',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_odds',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
