# Generated by Django 5.0.4 on 2024-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_match_team1_odds_match_team2_odds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team1_odds',
            new_name='team1_odds_bet365',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2_odds',
            new_name='team1_odds_betano',
        ),
        migrations.AddField(
            model_name='match',
            name='team2_odds_bet365',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_odds_betano',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
