# Generated by Django 5.0.4 on 2024-09-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0032_alter_champion_ban_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1_odds_bet365',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_odds_bet365',
        ),
        migrations.AlterField(
            model_name='player',
            name='total_assists',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_cs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_deaths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_dmg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_games',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_kills',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
