# Generated by Django 5.0.4 on 2025-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0035_player_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_url',
            field=models.URLField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
