# Generated by Django 5.0.4 on 2025-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0036_match_match_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished_ata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='initial_data',
            field=models.BooleanField(default=False),
        ),
    ]
