# Generated by Django 5.0.4 on 2025-06-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0037_match_finished_ata_match_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='finished_ata',
            new_name='finished_data',
        ),
    ]
