# Generated by Django 5.0.4 on 2025-06-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0038_rename_finished_ata_match_finished_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
