# Generated by Django 5.0.4 on 2025-06-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0039_game_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='side_selection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
