# Generated by Django 5.0.4 on 2025-06-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0040_game_side_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='side_selection',
            new_name='team_1_side_selection',
        ),
        migrations.AddField(
            model_name='game',
            name='team_2_side_selection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
