# Generated by Django 5.0.4 on 2025-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0044_alter_champion_name_alter_item_name_alter_rune_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
