# Generated by Django 5.0.4 on 2025-06-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0046_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='bans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='bot_picks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='jgl_picks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='mid_picks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='sup_picks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='top_picks',
            field=models.IntegerField(default=0),
        ),
    ]
