# Generated by Django 5.0.4 on 2024-04-25 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='users_who_submitted',
            field=models.ManyToManyField(blank=True, related_name='matches_for_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
