# Generated by Django 5.0.4 on 2024-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_users_who_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/anon-user.webp', upload_to='profile_pictures/'),
        ),
    ]
