# Generated by Django 5.0.4 on 2024-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/anon-user.webp', upload_to='profile_pictures/'),
        ),
    ]
