# Generated by Django 5.0.4 on 2024-04-27 10:59

import predictionGame.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/anon-user.webp', null=True, upload_to=predictionGame.users.models.profile_picture_path),
        ),
    ]
