# Generated by Django 5.0.4 on 2025-06-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_username_profile_edited_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
